# Generated by Django 3.1.2 on 2020-10-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0005_auto_20201014_2324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="document",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
